import TuyAPI from 'tuyapi';
import type { Light, LightState, LightDriver, Brand, Capability } from '@lightbox/shared';
import { existsSync, readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIG_DIR = join(__dirname, '../../data');
const DEVICES_FILE = join(CONFIG_DIR, 'tuya-devices.json');

const RECONNECT_DELAY = 5000; // 5 seconds

interface TuyaDeviceConfig {
  name: string;
  id: string;
  key: string;
  ip?: string;
  version?: string;
  mapping?: Record<string, { code: string; type: string; values?: any }>;
}

interface TuyaDevice {
  config: TuyaDeviceConfig;
  api: any; // TuyAPI instance
  connected: boolean;
  state: LightState;
  reconnecting: boolean;
}

/**
 * Tuya local control driver using tuyapi.
 * Reads device configs from tuya-devices.json (generated by tinytuya wizard).
 */
export class TuyaDriver implements LightDriver {
  readonly brand: Brand = 'tuya';

  private devices: Map<string, TuyaDevice> = new Map();
  private configs: TuyaDeviceConfig[] = [];

  async initialize(): Promise<void> {
    if (!existsSync(DEVICES_FILE)) {
      console.log('Tuya: no devices.json found, run tinytuya wizard first');
      return;
    }

    try {
      this.configs = JSON.parse(readFileSync(DEVICES_FILE, 'utf-8'));
      console.log(`Tuya: loaded ${this.configs.length} device configs`);
    } catch (err) {
      console.error('Tuya: failed to parse devices.json:', err);
    }
  }

  private async reconnectDevice(id: string): Promise<void> {
    const device = this.devices.get(id);
    if (!device || device.reconnecting) return;

    device.reconnecting = true;

    try {
      await device.api.disconnect();
    } catch {
      // Ignore disconnect errors
    }

    setTimeout(async () => {
      try {
        await device.api.find();
        await device.api.connect();
        device.reconnecting = false;
      } catch (err: any) {
        console.log(`Tuya: ${device.config.name} reconnect failed: ${err.message}`);
        device.reconnecting = false;
        // Try again later
        setTimeout(() => this.reconnectDevice(id), RECONNECT_DELAY);
      }
    }, RECONNECT_DELAY);
  }

  async discover(): Promise<Light[]> {
    const lights: Light[] = [];

    for (const config of this.configs) {
      // Skip devices without IP (offline when wizard ran)
      if (!config.ip) {
        console.log(`Tuya: ${config.name} has no IP, skipping (power it on and re-run wizard)`);
        continue;
      }

      const id = `tuya:${config.id}`;

      try {
        const api = new TuyAPI({
          id: config.id,
          key: config.key,
          ip: config.ip,
          version: config.version || '3.3',
          issueRefreshOnConnect: true,
        });

        // Set up event handlers
        api.on('connected', () => {
          const device = this.devices.get(id);
          if (device) {
            device.connected = true;
            device.reconnecting = false;
          }
          console.log(`Tuya: ${config.name} connected`);
        });

        api.on('disconnected', () => {
          const device = this.devices.get(id);
          if (device) {
            device.connected = false;
            console.log(`Tuya: ${config.name} disconnected, will reconnect...`);
            this.reconnectDevice(id);
          }
        });

        api.on('data', (data: any) => {
          const device = this.devices.get(id);
          if (device && data.dps) {
            this.updateStateFromDps(device, data.dps);
          }
        });

        api.on('error', (err: Error) => {
          // Don't log undefined errors
          if (err?.message) {
            console.error(`Tuya: ${config.name} error:`, err.message);
          }
        });

        // Connect
        await api.find();
        await api.connect();

        const device: TuyaDevice = {
          config,
          api,
          connected: true,
          state: { on: false },
          reconnecting: false,
        };
        this.devices.set(id, device);

        // Get initial state
        try {
          const status = await api.get({ schema: true }) as { dps?: Record<string, any> } | undefined;
          if (status?.dps) {
            this.updateStateFromDps(device, status.dps);
          }
        } catch {
          // Some devices don't support schema get
        }

        lights.push({
          id,
          name: config.name,
          brand: 'tuya',
          capabilities: this.getCapabilities(config),
          state: device.state,
          reachable: true,
        });

        console.log(`Tuya: discovered ${config.name} at ${config.ip}`);
      } catch (err: any) {
        console.error(`Tuya: failed to connect to ${config.name}:`, err.message);
      }
    }

    return lights;
  }

  async getState(deviceId: string): Promise<LightState> {
    const device = this.devices.get(`tuya:${deviceId}`);
    if (!device) return { on: false };
    return device.state;
  }

  async setState(deviceId: string, state: Partial<LightState>, _transition?: number): Promise<void> {
    const device = this.devices.get(`tuya:${deviceId}`);
    if (!device?.connected) {
      throw new Error('Tuya device not connected');
    }

    const dps: Record<string, any> = {};
    const mapping = device.config.mapping || {};

    // Find the right DPS codes from mapping
    const switchDp = this.findDpByCode(mapping, 'switch_led');
    const brightDp = this.findDpByCode(mapping, 'bright_value_v2') || this.findDpByCode(mapping, 'bright_value');
    const colourDp = this.findDpByCode(mapping, 'colour_data_v2') || this.findDpByCode(mapping, 'colour_data');
    const tempDp = this.findDpByCode(mapping, 'temp_value_v2') || this.findDpByCode(mapping, 'temp_value');
    const workModeDp = this.findDpByCode(mapping, 'work_mode');

    if (state.on !== undefined && switchDp) {
      dps[switchDp] = state.on;
    }

    if (state.brightness !== undefined && brightDp) {
      // Tuya uses 10-1000 scale
      dps[brightDp] = Math.round(state.brightness * 10);
      // Also set work mode to white if changing brightness
      if (workModeDp) dps[workModeDp] = 'white';
    }

    if (state.color !== undefined && colourDp) {
      // Tuya colour_data_v2 format: JSON with h (0-360), s (0-1000), v (0-1000)
      dps[colourDp] = JSON.stringify({
        h: state.color.h,
        s: Math.round(state.color.s * 10), // 0-100 -> 0-1000
        v: device.state.brightness ? Math.round(device.state.brightness * 10) : 1000,
      });
      // Switch to colour mode
      if (workModeDp) dps[workModeDp] = 'colour';
    }

    if (state.temperature !== undefined && tempDp) {
      // Tuya uses 0-1000 for temp (warm to cool)
      // Convert Kelvin: 2700K=0, 6500K=1000
      const normalized = Math.round(((state.temperature - 2700) / 3800) * 1000);
      dps[tempDp] = Math.max(0, Math.min(1000, normalized));
      if (workModeDp) dps[workModeDp] = 'white';
    }

    if (Object.keys(dps).length > 0) {
      await device.api.set({ multiple: true, data: dps });
    }
  }

  async dispose(): Promise<void> {
    for (const device of this.devices.values()) {
      try {
        await device.api.disconnect();
      } catch {
        // Ignore disconnect errors
      }
    }
    this.devices.clear();
  }

  private getCapabilities(config: TuyaDeviceConfig): Capability[] {
    const caps: Capability[] = ['on_off'];
    const mapping = config.mapping || {};
    const codes = Object.values(mapping).map(m => m.code);

    if (codes.some(c => c.includes('bright'))) caps.push('brightness');
    if (codes.some(c => c.includes('colour'))) caps.push('color');
    if (codes.some(c => c.includes('temp'))) caps.push('temperature');

    return caps;
  }

  private findDpByCode(mapping: Record<string, any>, code: string): string | undefined {
    for (const [dp, info] of Object.entries(mapping)) {
      if (info.code === code) return dp;
    }
    return undefined;
  }

  private updateStateFromDps(device: TuyaDevice, dps: Record<string, any>): void {
    const mapping = device.config.mapping || {};

    for (const [dp, value] of Object.entries(dps)) {
      const info = mapping[dp];
      if (!info) continue;

      switch (info.code) {
        case 'switch_led':
          device.state.on = Boolean(value);
          break;
        case 'bright_value_v2':
        case 'bright_value':
          device.state.brightness = Math.round(Number(value) / 10);
          break;
        case 'colour_data_v2':
        case 'colour_data':
          try {
            const color = typeof value === 'string' ? JSON.parse(value) : value;
            device.state.color = {
              h: color.h,
              s: Math.round(color.s / 10), // 0-1000 -> 0-100
            };
          } catch {
            // Invalid color data
          }
          break;
        case 'temp_value_v2':
        case 'temp_value':
          // Convert 0-1000 to Kelvin
          device.state.temperature = 2700 + Math.round((Number(value) / 1000) * 3800);
          break;
      }
    }
  }
}
