#!/usr/bin/env python3
"""Convert an image to src/picture/image.h (RGB565, fit to the panel, ordered-dithered).

  python3 tools/img2header.py photo.png [--size 240x320]
Uses pillow + numpy (installed in the pio venv: ~/.local/share/pio-venv/bin/python).
"""
import sys, os
from PIL import Image
import numpy as np

src = sys.argv[1]
W, H = 240, 320
if '--size' in sys.argv: W, H = map(int, sys.argv[sys.argv.index('--size') + 1].split('x'))
im = Image.open(src).convert('RGB')
s = min(W / im.width, H / im.height)
nw, nh = round(im.width * s), round(im.height * s)
im = im.resize((nw, nh), Image.LANCZOS)
canvas = Image.new('RGB', (W, H), (0, 0, 0)); canvas.paste(im, ((W - nw) // 2, (H - nh) // 2))
a = np.asarray(canvas).astype(np.int32)
bay = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]])
tile = np.tile(bay, (H // 4 + 1, W // 4 + 1))[:H, :W]
r = np.clip(a[:, :, 0] + tile // 2, 0, 255) >> 3
g = np.clip(a[:, :, 1] + tile // 4, 0, 255) >> 2
b = np.clip(a[:, :, 2] + tile // 2, 0, 255) >> 3
vals = ((r << 11) | (g << 5) | b).flatten()
lines = ['  ' + ','.join('0x%04X' % v for v in vals[i:i + 16]) + ',' for i in range(0, len(vals), 16)]
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'picture', 'image.h')
open(out, 'w').write('// Generated by tools/img2header.py from %s -- %dx%d RGB565, fit, ordered-dithered.\n#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\nconstexpr int IMG_W=%d, IMG_H=%d;\nstatic const uint16_t IMG[IMG_W*IMG_H] PROGMEM = {\n%s\n};\n' % (os.path.basename(src), W, H, W, H, '\n'.join(lines)))
print('wrote', out, '(%dx%d fitted to %dx%d)' % (nw, nh, W, H))
